fixed_hyperparams:
  vocab_size: 32000
  p_drop: 0.1
  batch_size: 16
  seq_len: 256
  lr: 0.0005

runs:
  - d_model: 128
    n_heads: 2
    n_blocks: 2
    total_batches: 1000
  - d_model: 128
    n_heads: 2
    n_blocks: 2
    total_batches: 2000


