name: ml
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.11.10
  - pytorch=2.5.1
  - numpy=2.1.3
  - tokenizers=0.21.0
  - transformers=4.51.1
  - pip=24.2
  - pip:
      - datasets==3.2.0
      - matplotlib==3.10.0
      - zstandard==0.23.0